version: '3'
services:
  back:
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile-Test
    environment:
      INCIPIT_DB_HOST: db
      INCIPIT_DB_PORT: 3306
    volumes:
      - .:/go/src/github.com/usagiga/Incipit
  db:
    image: mariadb/server:10.4
    environment:
      MARIADB_DATABASE: incipit
      MARIADB_USER: incipit
      MARIADB_PASSWORD: incipit-password
      MARIADB_ROOT_PASSWORD: incipit-password
    restart: always
