version: '3'
services:
  back:
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile-Test
    environment:
      INCIPIT_HOST: example.com
      INCIPIT_PORT: 8080
      INCIPIT_MYSQL_HOST: db
      INCIPIT_MYSQL_PORT: 3306
      INCIPIT_MYSQL_USER: incipit
      INCIPIT_MYSQL_PASS: incipit-password
    volumes:
      - .:/go/src/github.com/usagiga/Incipit
  db:
    image: mariadb/server:10.4
    environment:
      MARIADB_DATABASE: incipit
      MARIADB_USER: incipit
      MARIADB_PASSWORD: incipit-password
      MARIADB_ROOT_PASSWORD: incipit-password
    restart: always
