name: Backend (go build & go test)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      db:
        image: mariadb/server:10.4
        env:
          MARIADB_DATABASE: incipit
          MARIADB_USER: incipit
          MARIADB_PASSWORD: incipit-password
          MARIADB_ROOT_PASSWORD: incipit-password
        ports:
          - 3306:3306
    steps:
      - name: Set up Go ^1.14
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run go build
        run: make back_build
      - name: Run go test
        run: make back_test
        env:
          INCIPIT_MYSQL_HOST: 127.0.0.1
          INCIPIT_MYSQL_PORT: 3306
          INCIPIT_MYSQL_USER: incipit
          INCIPIT_MYSQL_PASS: incipit-password
